### ISSUE TITLE
Incorrect vector length seen in VCD

### ISSUE THREAD

**Issue by Harshitha172000** [YosysHQ/sby#123] opened 2021-05-28 07:53 UTC
I asserted some properties to check the following code.

``` 
for (i = 0; i < NUMWAYS; i = i + 1) begin         
       if (access[i]) begin         
           for (j = 0; j < NUMWAYS; j = j + 1) begin              
                 if (i != j) begin                  
                   expand[i][j] = 1'b0;              
                 end       
          end         
           for (j = 0; j < NUMWAYS; j = j + 1) begin          
                 if (i != j) begin                
                    expand[j][i] = 1'b1;               
                end           
         end        
 end      
end 
```
I ended up with the following error where the last row of the expand vector has only 3 bits instead of 4.

![expand_error](https://user-images.githubusercontent.com/59602295/119948589-99c96d80-bfb6-11eb-9379-8859b010cdcc.jpg)

Later, I asserted properties to check whether all vectors of the expand array are of the same length, then the test passed.

VCD showing up incorrect vector length for the above code snippet.

**Comment by jix** [comment] 2022-08-08 10:17
I can't reproduce this nor see how this could happen with the current version of sby and yosys. There have been changes in the meantime, so it might have been fixed by one of those. If this issue still persists with a current sby and yosys version, please provide a complete runnable example, not just a snippet.

**Closed by jix** 2022-08-08 10:17 UTC
